/** The skill vocabulary. QnA gap extraction is constrained to these slugs. */
export const SKILL_SEED: { slug: string; name: string; category: string }[] = [
  { slug: 'html', name: 'HTML', category: 'frontend' },
  { slug: 'css', name: 'CSS', category: 'frontend' },
  { slug: 'javascript', name: 'JavaScript', category: 'frontend' },
  { slug: 'typescript', name: 'TypeScript', category: 'frontend' },
  { slug: 'react', name: 'React', category: 'frontend' },
  { slug: 'nextjs', name: 'Next.js', category: 'frontend' },
  { slug: 'tailwind', name: 'Tailwind CSS', category: 'frontend' },
  { slug: 'accessibility', name: 'Web Accessibility', category: 'frontend' },
  { slug: 'nodejs', name: 'Node.js', category: 'backend' },
  { slug: 'rest-apis', name: 'REST APIs', category: 'backend' },
  { slug: 'graphql', name: 'GraphQL', category: 'backend' },
  { slug: 'authentication', name: 'Authentication & Authorization', category: 'backend' },
  { slug: 'sql', name: 'SQL', category: 'data' },
  { slug: 'postgres', name: 'PostgreSQL', category: 'data' },
  { slug: 'redis', name: 'Redis', category: 'data' },
  { slug: 'mongodb', name: 'MongoDB', category: 'data' },
  { slug: 'data-modeling', name: 'Data Modeling', category: 'data' },
  { slug: 'python', name: 'Python', category: 'languages' },
  { slug: 'java', name: 'Java', category: 'languages' },
  { slug: 'go', name: 'Go', category: 'languages' },
  { slug: 'rust', name: 'Rust', category: 'languages' },
  { slug: 'c-plus-plus', name: 'C++', category: 'languages' },
  { slug: 'data-structures', name: 'Data Structures', category: 'cs-fundamentals' },
  { slug: 'algorithms', name: 'Algorithms', category: 'cs-fundamentals' },
  { slug: 'operating-systems', name: 'Operating Systems', category: 'cs-fundamentals' },
  { slug: 'computer-networks', name: 'Computer Networks', category: 'cs-fundamentals' },
  { slug: 'system-design', name: 'System Design', category: 'architecture' },
  { slug: 'microservices', name: 'Microservices', category: 'architecture' },
  { slug: 'message-queues', name: 'Message Queues & Streams', category: 'architecture' },
  { slug: 'caching', name: 'Caching Strategies', category: 'architecture' },
  { slug: 'docker', name: 'Docker', category: 'devops' },
  { slug: 'kubernetes', name: 'Kubernetes', category: 'devops' },
  { slug: 'ci-cd', name: 'CI/CD', category: 'devops' },
  { slug: 'linux', name: 'Linux', category: 'devops' },
  { slug: 'aws', name: 'AWS', category: 'cloud' },
  { slug: 'terraform', name: 'Terraform', category: 'cloud' },
  { slug: 'git', name: 'Git & Version Control', category: 'tooling' },
  { slug: 'testing', name: 'Automated Testing', category: 'quality' },
  { slug: 'debugging', name: 'Debugging', category: 'quality' },
  { slug: 'security', name: 'Application Security', category: 'security' },
  { slug: 'machine-learning', name: 'Machine Learning', category: 'ai' },
  { slug: 'deep-learning', name: 'Deep Learning', category: 'ai' },
  { slug: 'nlp', name: 'Natural Language Processing', category: 'ai' },
  { slug: 'prompt-engineering', name: 'Prompt Engineering', category: 'ai' },
  { slug: 'pandas', name: 'Pandas & Data Analysis', category: 'data-science' },
  { slug: 'statistics', name: 'Statistics', category: 'data-science' },
  { slug: 'communication', name: 'Technical Communication', category: 'soft-skills' },
  { slug: 'problem-solving', name: 'Problem Solving', category: 'soft-skills' },
];
